Repository doctrine/doctrine-website, pull requests merged in 2018-08, with the labels that each got.

#198 Show warning for outdated and upcoming docs versions
  source/_layouts/documentation.html
Labels: enhancement

#199 Move search result container out of sticky area
  source/_layouts/layout.html
  source/css/style.css
Labels: bug, user experience

#203 Update doctrine/RST to doctrine/rst-parser.
  app/config/sculpin_kernel.yml
  app/src/Doctrine/Website/Docs/RSTBuilder.php
  app/src/Doctrine/Website/Docs/SearchIndexer.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/CautionDirective.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/CodeBlockDirective.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/ConfigurationBlockDirective.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/HintDirective.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/IndexDirective.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/NoteDirective.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/NoticeDirective.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/RoleDirective.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/SectionAuthorDirective.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/TipDirective.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/TocDirective.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/TocHeaderDirective.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/VersionAddedDirective.php
  app/src/Doctrine/Website/DoctrineSculpinBundle/Directive/WarningDirective.php
  app/src/Doctrine/Website/RST/Kernel.php
  composer.json
  composer.lock
  tests/Doctrine/Website/Tests/Docs/RSTBuilderTest.php
  tests/Doctrine/Website/Tests/Docs/SearchIndexerTest.php
Labels: enhancement

#208 Show which project and version you are searching in the search box placeholder
  lib/Twig/MainExtension.php
  source/js/search.js
  templates/layouts/layout.html.twig
  tests/FunctionalTest.php
  tests/Twig/MainExtensionTest.php
Labels: enhancement

#206 Explicitly set search box color to black
  source/css/style.css
Labels: bug

#214 Use spaceship operator instead of strcmp function.
  lib/Sitemap/SitemapPageRepository.php
Labels: improvement

#213 Fix plain code blocks that only use :: so they render properly
  .gitignore
  lib/Docs/RSTBuilder.php
  tests/Docs/RSTBuilderTest.php
  tests/Docs/resources/docs/example-project/en/1.0/index.rst
  tests/Docs/resources/example-project/docs/en/index.rst
  tests/Docs/resources/sculpin-source/projects/example-project/en/1.0/about.html
  tests/Docs/resources/sculpin-source/projects/example-project/en/1.0/cookbook/article.html
  tests/Docs/resources/sculpin-source/projects/example-project/en/1.0/cookbook/nested/nested.html
  tests/Docs/resources/sculpin-source/projects/example-project/en/1.0/cross-ref.html
  tests/Docs/resources/sculpin-source/projects/example-project/en/1.0/example.html
  tests/Docs/resources/sculpin-source/projects/example-project/en/1.0/index.html
  tests/Docs/resources/sculpin-source/projects/example-project/en/1.0/reference/getting-started.html
Labels: enhancement

#217 Add edit links to all pages on the site.
  lib/Builder/SourceFile.php
  lib/Builder/SourceFileRenderer.php
  lib/Builder/SourceFileRepository.php
  templates/layouts/documentation.html.twig
  templates/layouts/layout.html.twig
  tests/Blog/BlogPostRepositoryTest.php
  tests/Builder/SourceFileRendererTest.php
  tests/Builder/SourceFileTest.php
Labels: Enhancement

#218 Allow each project to include a doctrine-project.json file in the roo…
  lib/Projects/ProjectFactory.php
  lib/Projects/ProjectJsonReader.php
  tests/Projects/ProjectFactoryTest.php
  tests/Projects/ProjectJsonReaderTest.php
  tests/Projects/ProjectRepositoryTest.php
  tests/test-projects/invalid-project-json/doctrine-project.json
  tests/test-projects/test-project/doctrine-project.json
Labels: Enhancement

#220 Read composer json data to try and get data for the website.
  lib/Projects/ProjectFactory.php
  lib/Projects/ProjectJsonReader.php
  tests/Projects/ProjectFactoryTest.php
  tests/Projects/ProjectJsonReaderTest.php
  tests/test-projects/invalid-project-json/.doctrine-project.json
  tests/test-projects/test-project/.doctrine-project.json
  tests/test-projects/test-project/composer.json
Labels: Enhancement

#221 Add better default values to require less explicit configuration per …
  config/projects.yml
  lib/Projects/Project.php
Labels: Improvement
