Repository doctrine/doctrine-website, pull requests merged in 2018-09, with the labels that each got.

#224 Expand "Who uses Doctrine" section
  source/index.html
Labels: Improvement

#216 Ensure we have integrity and crossorigin params on all our css and js.
  lib/Assets/AssetIntegrityGenerator.php
  lib/Twig/MainExtension.php
  templates/layouts/documentation.html.twig
  templates/layouts/layout.html.twig
  tests/Assets/AssetIntegrityGeneratorTest.php
  tests/Builder/SourceFileRepositoryTest.php
  tests/Twig/MainExtensionTest.php
  tests/source/css/style.css
Labels: Enhancement

#226 Fix blog index style so it looks like it did before migrating away fr…
  lib/Blog/BlogPostRepository.php
  lib/Controllers/AtomController.php
  lib/Controllers/BlogController.php
  lib/Controllers/HomepageController.php
  lib/Twig/MainExtension.php
  source/archive.html
  source/blog.html
  templates/layouts/blog-post.html.twig
  tests/Blog/BlogPostRepositoryTest.php
Labels: Improvement

#227 Add paypal button to the homepage.
  source/index.html
Labels: Enhancement

#230 Expand CS team members
  config/team_members.yml
Labels: Improvement

#239 Add DoctrineMongoDBBundle to the Doctrine website.
  config/projects.yml
  config/services.xml
  lib/Commands/ClearBuildCacheCommand.php
  lib/Docs/CodeBlockLanguageDetector.php
  lib/Projects/Project.php
  lib/Projects/ProjectDataReader.php
  lib/RST/Directive/AdmonitionDirective.php
  lib/RST/Directive/SeeAlsoDirective.php
  lib/RST/Directive/SidebarDirective.php
  source/projects/doctrine-mongodb-bundle.html
  tests/Projects/ProjectDataReaderTest.php
Labels: Enhancement

#240 Fix Psalm typo.
  source/policies/deprecation.rst
Labels: Documentation

#241 Always checkout the version branch and only update from git when --sy…
  lib/Docs/BuildDocs.php
  lib/Projects/ProjectGitSyncer.php
  lib/Projects/ProjectVersion.php
  tests/Docs/BuildDocsTest.php
  tests/Projects/ProjectGitSyncerTest.php
  tests/Projects/ProjectVersionTest.php
Labels: Enhancement

#243 Add CouchDB Client to the website.
  config/projects.yml
  source/projects/couchdb-client.html
Labels: Enhancement

#242 Fix the styling of alert html.
  templates/alert.html.twig
  templates/layouts/documentation.html.twig
  templates/layouts/project.html.twig
Labels: Bug

#245 Improve styling and organization of projects page.
  source/projects.html
Labels: Enhancement

#246 Enhance projects list
  config/projects.yml
  config/services.xml
  lib/Projects/ProjectDataReader.php
  lib/Projects/ProjectFactory.php
  lib/Projects/ProjectIntegration.php
  lib/Projects/ProjectIntegrationType.php
  source/projects.html
  templates/layouts/project.html.twig
  templates/projects-list.html.twig
  templates/projects-short-list.html.twig
  tests/Projects/ProjectDataReaderTest.php
  tests/Projects/ProjectFactoryTest.php
Labels: Enhancement

#248 Add the Doctrine Skeleton Mapper to the website.
  config/projects.yml
  config/team_members.yml
  source/projects/skeleton-mapper.html
Labels: Enhancement

#252 Update readme to include additional configuration information for bui…
  .travis.yml
  config/local.yml.dist
  source/contribute/website.rst
Labels: Improvement
