Repository doctrine/doctrine-website, pull requests merged in 2019-01, with the labels that each got.

#276 Rename doctrine2 repo to orm.
  config/projects.yml
Labels: Improvement

#283 Document our policy around why we commit the composer.lock file.
  source/policies.html
  source/policies.rst
Labels: Documentation

#284 CI: Use Ubuntu 16.04
  .travis.yml
Labels: Improvement

#285 Add sponsorship page to document all ways you can sponsor Doctrine.
  config/routes.yml
  lib/Controllers/SponsorshipController.php
  source/sponsorship.rst
  templates/layouts/layout.html.twig
Labels: Improvement

#259 Add Zend Framework integrations to the website.
  config/projects.yml
  lib/Docs/RST/RSTCopier.php
  lib/Projects/ProjectDataReader.php
  source/images/symfony-logo.png
  source/images/zend-framework-logo.png
  templates/projects-short-list.html.twig
Labels: Enhancement, WIP
