Repository doctrine/doctrine-website, pull requests merged in 2019-04, with the labels that each got.

#290 Spell "maintainers" properly
  config/routes.yml
Labels: Improvement

#291 Trying to figure out why GitHub api sometimes does not return results.
  config/config.yml
  lib/Github/ProdGithubProjectContributors.php
  tests/Github/ProdGithubProjectContributorsTest.php
Labels: Improvement

#292 Handle 0.x releases better in the website.
  lib/Git/Tag.php
  lib/Model/ProjectVersion.php
  lib/Projects/ProjectVersionsReader.php
  templates/layouts/documentation.html.twig
  templates/project.html.twig
  tests/Git/TagTest.php
  tests/Projects/ProjectVersionsReaderTest.php
Labels: Enhancement

#293 Remove sami and api docs from website.
  config/routes.yml
  lib/Cache/CacheClearer.php
  lib/Commands/BuildDocsCommand.php
  lib/Deployer.php
  lib/Docs/APIBuilder.php
  lib/Docs/BuildDocs.php
  lib/WebsiteBuilder.php
  templates/project-version.html.twig
  templates/project.html.twig
  templates/projects-list.html.twig
  templates/projects-short-list.html.twig
  tests/Cache/CacheClearerTest.php
  tests/DataSources/SitemapPagesTest.php
  tests/DeployerTest.php
  tests/Docs/APIBuilderTest.php
  tests/Docs/BuildDocsTest.php
Labels: Improvement

#267 Upgrade RST Parser.
  .scrutinizer.yml
  .travis.yml
  composer.json
  composer.lock
  config/services.xml
  lib/DataBuilder/ProjectContributorDataBuilder.php
  lib/Docs/RST/RSTBuilder.php
  lib/Docs/RST/RSTCopier.php
  lib/Docs/RST/RSTPostBuildProcessor.php
  lib/Docs/SearchIndexer.php
  lib/Github/GithubProjectContributors.php
  lib/Github/ProdGithubProjectContributors.php
  lib/Github/TestGithubProjectContributors.php
  lib/ProcessFactory.php
  lib/RST/Directive/AdmonitionDirective.php
  lib/RST/Directive/CodeBlockDirective.php
  lib/RST/Directive/ConfigurationBlockDirective.php
  lib/RST/Directive/IndexDirective.php
  lib/RST/Directive/RoleDirective.php
  lib/RST/Directive/SectionAuthorDirective.php
  lib/RST/Directive/TocDirective.php
  lib/RST/Directive/TocHeaderDirective.php
  lib/RST/Directive/VersionAddedDirective.php
  lib/RST/Kernel.php
  source/js/sidebar.js
  source/styles/index.scss
  tests/DataBuilder/ProjectContributorDataBuilderTest.php
  tests/Docs/RST/RSTBuilderTest.php
  tests/Docs/SearchIndexerTest.php
  tests/Docs/resources/search-indexer/index.rst
  tests/FunctionalTest.php
  tests/Github/ProdGithubProjectContributorsTest.php
Labels: Improvement, WIP

#294 Fix bug with major release zero versions that do not have an associated branch.
  lib/Projects/ProjectVersionsReader.php
  tests/Projects/ProjectVersionsReaderTest.php
Labels: Bug

#295 Copy website data to the build directory.
  lib/WebsiteBuilder.php
  tests/WebsiteBuilderTest.php
Labels: Improvement
