Repository doctrine/doctrine-website, pull requests merged in 2023-08, with the labels that each got.

#496 Run dev tools on PHP 8.2
  .github/workflows/coding-standards.yml
  .github/workflows/static-analysis.yml
  phpcs.xml.dist
Labels: Build

#497 Bump node to v14
  .github/workflows/continuous-integration.yml
  .github/workflows/deployment.yml
Labels: Build

#498 Bump all frontend deps
  yarn.lock
Labels: dependencies

#499 Prettier 3
  package.json
  source/js/event.js
  source/js/index.js
  source/js/main.js
  source/js/search.js
  source/js/sidebar.js
  source/styles/index.scss
  tests/Twig/MainExtensionTest.php
  yarn.lock
Labels: dependencies

#507 PHPUnit 10.3
  .gitignore
  composer.json
  composer.lock
  phpunit.xml.dist
  tests/Cache/CacheClearerTest.php
  tests/Docs/CodeBlockRendererTest.php
  tests/FunctionalTest.php
  tests/Twig/ProjectExtensionTest.php
  tests/WebsiteBuilderTest.php
Labels: dependencies

#518 Enable symlink-alias functional test
  tests/FunctionalTest.php
Labels: Tests
